/*Função pra rolar dados aleatórios*/
function rolldice(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

let nd = document.getElementById('nd')
let dificuldade = document.getElementById('dificuldade')

const tabela = {
  1: { Low: 13, Moderate: 18, Severe: 26, Extreme: 35 },
  2: { Low: 23, Moderate: 30, Severe: 45, Extreme: 60 },
  3: { Low: 38, Moderate: 50, Severe: 75, Extreme: 100 },
  4: { Low: 65, Moderate: 85, Severe: 130, Extreme: 170 },
  5: { Low: 100, Moderate: 135, Severe: 200, Extreme: 270 },
  6: { Low: 150, Moderate: 200, Severe: 300, Extreme: 400 },
  7: { Low: 220, Moderate: 290, Severe: 440, Extreme: 580 },
  8: { Low: 300, Moderate: 400, Severe: 600, Extreme: 800 },
  9: { Low: 430, Moderate: 570, Severe: 860, Extreme: 1140 },
  10: { Low: 600, Moderate: 800, Severe: 1200, Extreme: 1600 },
  11: { Low: 865, Moderate: 1150, Severe: 1725, Extreme: 2300 },
  12: { Low: 1250, Moderate: 1650, Severe: 2475, Extreme: 3300 },
  13: { Low: 1875, Moderate: 2500, Severe: 3750, Extreme: 5000 },
  14: { Low: 2750, Moderate: 3650, Severe: 5500, Extreme: 7300 },
  15: { Low: 4100, Moderate: 5450, Severe: 8200, Extreme: 10900 },
  16: { Low: 6200, Moderate: 8250, Severe: 12400, Extreme: 16400 },
  17: { Low: 9600, Moderate: 12800, Severe: 19200, Extreme: 25600 },
  18: { Low: 15600, Moderate: 20800, Severe: 31200, Extreme: 41600 },
  19: { Low: 26600, Moderate: 35500, Severe: 53500, Extreme: 71000 },
  20: { Low: 36800, Moderate: 49000, Severe: 73000, Extreme: 98000 }
}

const itens0 = [
  ["Adze", 1, "Common"],
  ["Battle Axe", 1, "Common"],
  ["Beehive", 1, "Common"],
  ["Boarding Axe", 1, "Uncommon"],
  ["Brass Ear", 1, "Common"],
  ["Buckler", 1, "Common"],
  ["Compass", 1, "Common"],
  ["Cookware", 1, "Common"],
  ["Dart Umbrella", 1, "Uncommon"],
  ["Depth Gauge", 1, "Uncommon"],
  ["Fake Blood Pack", 1, "Common"],
  ["Filcher's Fork", 1, "Uncommon"],
  ["Flayleaf", 1, "Common"],
  ["Flyssa", 1, "Common"],
  ["Formula Book (Blank)", 1, "Common"],
  ["Gada", 1, "Common"],
  ["Gaff", 1, "Common"],
  ["Gladius", 1, "Common"],
  ["Glaive", 1, "Common"],
  ["Greatclub", 1, "Common"],
  ["Greatpick", 1, "Common"],
  ["Griffon Cane", 1, "Common"],
  ["Harpoon", 1, "Common"],
  ["Harrow Carrying Case", 1, "Common"],
  ["Harrow Deck (Simple)", 1, "Common"],
  ["Kama", 1, "Uncommon"],
  ["Lance", 1, "Common"],
  ["Lantern (Bull's-Eye)", 1, "Common"],
  ["Lion Scythe", 1, "Uncommon"],
  ["Lizard (X's)", 1, "Common"],
  ["Longsword", 1, "Common"],
  ["Mace", 1, "Common"],
  ["Marked Playing Cards", 1, "Common"],
  ["Mirror", 1, "Common"],
  ["Morningstar", 1, "Common"],
  ["Net", 1, "Common"],
  ["Nightstick", 1, "Uncommon"],
  ["Ogre Hook", 1, "Uncommon"],
  ["Paint Set", 1, "Common"],
  ["Panabas", 1, "Common"],
  ["Rabbit", 1, "Common"],
  ["Religious Text", 1, "Common"],
  ["Rope Dart", 1, "Uncommon"],
  ["Rubbing Set", 1, "Uncommon"],
  ["Scimitar", 1, "Common"],
  ["Shootist Bandolier", 1, "Uncommon"],
  ["Snake", 1, "Common"],
  ["Spellbook (Blank)", 1, "Common"],
  ["Spraysling", 1, "Uncommon"],
  ["Storage", 1, "Common"],
  ["Tank (Stationary)", 1, "Common"],
  ["Tool (Long)", 1, "Common"],
  ["Trident", 1, "Common"],
  ["Trundle Wheel", 1, "Common"],
  ["Wakizashi", 1, "Uncommon"],
  ["War Javelin", 1, "Common"],
  ["Warhammer", 1, "Common"],
  ["Wax Key Blank", 1, "Uncommon"],
  ["Wooden Shield", 1, "Common"],
  ["Writing Set", 1, "Common"],
  ["Zhuazhi Bang", 1, "Uncommon"],
  ["Fighting Fan", 1, "Uncommon"],
  ["Fauchard", 1, "Common"],
  ["Adventurer's Pack", 1, "Common"],
  ["Badger", 1, "Common"],
  ["Scroll Robes", 1, "Common"],
  ["Traitor's Ring", 1, "Uncommon"],
  ["Armored Cloak", 2, "Common"],
  ["Armored Skirt", 2, "Common"],
  ["Bladed Diabolo", 2, "Uncommon"],
  ["Broadspear", 2, "Common"],
  ["Butterfly Sword", 2, "Uncommon"],
  ["Caster's Targe", 2, "Common"],
  ["Catch Pole", 2, "Common"],
  ["Clan Dagger", 2, "Uncommon"],
  ["Claw Blade", 2, "Uncommon"],
  ["Clothing (Fine)", 2, "Common"],
  ["Combat Lure", 2, "Uncommon"],
  ["Disguise Kit", 2, "Common"],
  ["Dueling Spear", 2, "Uncommon"],
  ["Extendible Pincer", 2, "Uncommon"],
  ["Feng Huo Lun", 2, "Uncommon"],
  ["Gill Hook", 2, "Uncommon"],
  ["Gnome Hooked Hammer", 2, "Uncommon"],
  ["Greataxe", 2, "Common"],
  ["Greatsword", 2, "Common"],
  ["Guisarme", 2, "Common"],
  ["Halberd", 2, "Common"],
  ["Hide Armor", 2, "Common"],
  ["Hide Shield", 2, "Common"],
  ["Horse", 2, "Common"],
  ["Jellyfish Lamp", 2, "Common"],
  ["Karambit", 2, "Uncommon"],
  ["Katana", 2, "Uncommon"],
  ["Kestros", 2, "Common"],
  ["Khakkara", 2, "Uncommon"],
  ["Khopesh", 2, "Uncommon"],
  ["Kusarigama", 2, "Uncommon"],
  ["Leather Armor", 2, "Common"],
  ["Leiomano", 2, "Uncommon"],
  ["Mask (Fine)", 2, "Common"],
  ["Musical Instrument (Heavy)", 2, "Common"],
  ["Opossum, domestic", 2, "Common"],
  ["Orc Necksplitter", 2, "Uncommon"],
  ["Pantograph Gauntlet", 2, "Uncommon"],
  ["Plated Duster", 2, "Uncommon"],
  ["Ranseur", 2, "Common"],
  ["Rapier", 2, "Common"],
  ["Rattan Armor", 2, "Common"],
  ["Reinforced Surcoat", 2, "Uncommon"],
  ["Religious Symbol (Silver)", 2, "Common"],
  ["Repair Toolkit", 2, "Common"],
  ["Sansetsukon", 2, "Uncommon"],
  ["Scythe", 2, "Common"],
  ["Shauth Blade", 2, "Uncommon"],
  ["Spirit Thresher", 2, "Uncommon"],
  ["Starknife", 2, "Common"],
  ["Steel Shield", 2, "Common"],
  ["Talwar", 2, "Common"],
  ["Temple Sword", 2, "Uncommon"],
  ["Urumi", 2, "Uncommon"],
  ["Visap", 2, "Uncommon"],
  ["War Flail", 2, "Common"],
  ["Wish Knife", 2, "Uncommon"],
  ["Bladed Hoop", 2, "Uncommon"],
  ["Alchemist's Toolkit", 3, "Common"],
  ["Bat", 3, "Common"],
  ["Bladed Scarf", 3, "Uncommon"],
  ["Comealong", 3, "Uncommon"],
  ["Concealment Coin", 3, "Uncommon"],
  ["Crossbow", 3, "Common"],
  ["Dancer's Spear", 3, "Common"],
  ["Dwarven Waraxe", 3, "Uncommon"],
  ["Elven Branched Spear", 3, "Uncommon"],
  ["Falcata", 3, "Common"],
  ["Falchion", 3, "Common"],
  ["Folding Ladder", 3, "Common"],
  ["Gnome Flickmace", 3, "Uncommon"],
  ["Grappling Gun", 3, "Uncommon"],
  ["Hand Crossbow", 3, "Common"],
  ["Hollowed Hilt", 3, "Uncommon"],
  ["Hook Sword", 3, "Uncommon"],
  ["Hourglass", 3, "Common"],
  ["Injection Spear", 3, "Uncommon"],
  ["Kalis", 3, "Uncommon"],
  ["Kilted Breastplate", 3, "Common"],
  ["Klar", 3, "Common"],
  ["Leather Lamellar", 3, "Common"],
  ["Liuyedao", 3, "Common"],
  ["Macuahuitl", 3, "Common"],
  ["Maul", 3, "Common"],
  ["Meteor Hammer", 3, "Common"],
  ["Monkey", 3, "Common"],
  ["Naginata", 3, "Uncommon"],
  ["Quilted Armor", 3, "Common"],
  ["Shortbow", 3, "Common"],
  ["Shuan Ji", 3, "Uncommon"],
  ["Spiked Chain", 3, "Uncommon"],
  ["Studded Leather Armor", 3, "Common"],
  ["Sun Sling", 3, "Uncommon"],
  ["Tetsubo", 3, "Uncommon"],
  ["Thieves' Toolkit", 3, "Common"],
  ["Whipstaff", 3, "Uncommon"],
  ["Wrist Launcher", 3, "Uncommon"],
  ["Artisan's Toolkit", 4, "Common"],
  ["Bastard Sword", 4, "Common"],
  ["Bec de Corbin", 4, "Common"],
  ["Buckle Armor", 4, "Common"],
  ["Buugeng", 4, "Uncommon"],
  ["Chain", 4, "Common"],
  ["Crescent Cross", 4, "Common"],
  ["Donchak", 4, "Uncommon"],
  ["Earthbreaker", 4, "Common"],
  ["Elven Curve Blade", 4, "Uncommon"],
  ["Fangwire", 4, "Uncommon"],
  ["Heavy Crossbow", 4, "Common"],
  ["Heavy Rondache", 4, "Common"],
  ["Leaf Weave", 4, "Common"],
  ["Meteor Shield", 4, "Common"],
  ["Rhoka Sword", 4, "Uncommon"],
  ["Scale Mail", 4, "Common"],
  ["Tack", 4, "Common"],
  ["Tengu Gale Blade", 4, "Uncommon"],
  ["Umbrella Injector", 4, "Uncommon"],
  ["War Lance", 4, "Uncommon"],
  ["Zulfikar", 4, "Uncommon"],
  ["Air Repeater", 5, "Uncommon"],
  ["Aklys", 5, "Uncommon"],
  ["Alchemist's Lab", 5, "Common"],
  ["Animal Blind", 5, "Common"],
  ["Bladed Gauntlet", 5, "Uncommon"],
  ["Buoyancy Vest", 5, "Common"],
  ["Chain Shirt", 5, "Common"],
  ["Clan Pistol", 5, "Uncommon"],
  ["Coral Armor", 5, "Common"],
  ["Familiar Satchel", 5, "Uncommon"],
  ["Fire Lance", 5, "Uncommon"],
  ["Fire Poi", 5, "Uncommon"],
  ["Gauntlet Buckler", 5, "Common"],
  ["Glass Cutter", 5, "Uncommon"],
  ["Halfling Sling Staff", 5, "Uncommon"],
  ["Hand Cannon", 5, "Uncommon"],
  ["Harnessed Shield", 5, "Common"],
  ["Healer's Toolkit", 5, "Common"],
  ["Kayalini", 5, "Common"],
  ["Knight's Standard", 5, "Uncommon"],
  ["Long Hammer", 5, "Common"],
  ["Membership Cords", 5, "Uncommon"],
  ["Niyaháat", 5, "Common"],
  ["Niyaháat", 5, "Common"],
  ["Pelagic Helmet", 5, "Common"],
  ["Raccoon", 5, "Common"],
  ["Razor Disc", 5, "Common"],
  ["Sankeit", 5, "Common"],
  ["Sankeit", 5, "Common"],
  ["Sawtooth Saber", 5, "Uncommon"],
  ["Shield Bow", 5, "Common"],
  ["Sickle-Saber", 5, "Uncommon"],
  ["Snare Kit", 5, "Common"],
  ["Spiral Rapier", 5, "Uncommon"],
  ["Swim Fins", 5, "Common"],
  ["Sword Cane", 5, "Common"],
  ["Tamchal Chakram", 5, "Uncommon"],
  ["Tent (Four-Person)", 5, "Common"],
  ["Thunder Sling", 5, "Uncommon"],
  ["Water Purifier", 5, "Uncommon"],
  ["Whip Claw", 5, "Uncommon"],
  ["Wish Blade", 5, "Uncommon"],
  ["Battle Saddle", 6, "Common"],
  ["Ceramic Plate", 6, "Common"],
  ["Chain Mail", 6, "Common"],
  ["Chain Sword", 6, "Uncommon"],
  ["Coat Pistol", 6, "Uncommon"],
  ["Flingflenser", 6, "Uncommon"],
  ["Flintlock Pistol", 6, "Uncommon"],
  ["Flying Talon", 6, "Uncommon"],
  ["Gakgung", 6, "Common"],
  ["Lattice Armor", 6, "Common"],
  ["Longbow", 6, "Common"],
  ["Nodachi", 6, "Common"],
  ["Salvo Shield", 6, "Common"],
  ["Shield Pistol", 6, "Uncommon"],
  ["Swordstealer Shield", 6, "Common"],
  ["Wooden Breastplate", 6, "Common"],
  ["Double-Barreled Pistol", 7, "Uncommon"],
  ["Flintlock Musket", 7, "Uncommon"],
  ["Lamellar Breastplate", 7, "Common"],
  ["Arbalest", 8, "Common"],
  ["Black Powder Knuckle Dusters", 8, "Uncommon"],
  ["Blunderbuss", 8, "Uncommon"],
  ["Bow Staff", 8, "Common"],
  ["Breaching Pike", 8, "Uncommon"],
  ["Breastplate", 8, "Common"],
  ["Butchering Axe", 8, "Uncommon"],
  ["Cane Pistol", 8, "Uncommon"],
  ["Cow", 8, "Common"],
  ["Dagger Pistol", 8, "Uncommon"],
  ["Daikyu", 8, "Uncommon"],
  ["Dart Shield", 8, "Common"],
  ["Dwarven Dorn-Dergar", 8, "Uncommon"],
  ["Harrow Mat", 8, "Common"],
  ["Lancer", 8, "Common"],
  ["Mikazuki", 8, "Common"],
  ["Rotary Bow", 8, "Common"],
  ["Shauth Lash", 8, "Uncommon"],
  ["Wrecker", 8, "Common"],
  ["Capturing Spetum", 9, "Uncommon"],
  ["Dragon Mouth Pistol", 9, "Uncommon"],
  ["Gauntlet Bow", 9, "Common"],
  ["Lattice Armor", 9, "Common"],
  ["Long Air Repeater", 9, "Uncommon"],
  ["Mithral Tree", 9, "Uncommon"],
  ["Arquebus", 10, "Uncommon"],
  ["Asp Coil", 10, "Uncommon"],
  ["Barding (Light; Small or Medium)", 10, "Common"],
  ["Bird (House Eagle)", 10, "Common"],
  ["Cat (Galtan Orange)", 10, "Common"],
  ["Dinosaur", 10, "Common"],
  ["False Manacles", 10, "Uncommon"],
  ["Field Guide", 10, "Uncommon"],
  ["Harmona Gun", 10, "Uncommon"],
  ["Harrow Deck (Common)", 10, "Common"],
  ["Rapier Pistol", 10, "Uncommon"],
  ["Snowshoes", 10, "Common"],
  ["Tank (Traveling)", 10, "Common"],
  ["Taw Launcher", 10, "Uncommon"],
  ["Tower Shield", 10, "Common"],
  ["Tricky Pick", 10, "Uncommon"],
  ["Triggerbrand", 10, "Uncommon"],
  ["Harrow Deck (Fine)", 11, "Common"],
  ["Hongali Hornbow", 11, "Uncommon"],
  ["Pepperbox", 12, "Uncommon"],
  ["Three-Section Naginata", 12, "Uncommon"],
  ["Mace Multipistol", 13, "Uncommon"],
  ["Battle Lute", 15, "Uncommon"],
  ["Piercing Wind", 15, "Uncommon"],
  ["Armored Coat", 20, "Uncommon"],
  ["Barding (Light; Large)", 20, "Common"],
  ["Clockwork Dial", 20, "Uncommon"],
  ["Sisterstone Chunk", 20, "Rare"],
  ["Spyglass", 20, "Common"],
  ["Alchemical Crossbow", 25, "Uncommon"]
]

const itens1 = [
  ["Elixir of Gender Transformation (Lesser)", 1, "Common"],
  ["Marvelous Miniature (Campfire)", 1, "Common"],
  ["Popdust", 1, "Uncommon"],
  ["Surprise Doll", 1, "Common"],
  ["Pesh Paste", 1, "Common"],
  ["Addiction Suppressant (Lesser)", 2, "Common"],
  ["Aldori Dueling Sword", 2, "Uncommon"],
  ["Eyecatcher", 2, "Uncommon"],
  ["Lock (Simple)", 2, "Common"],
  ["Magnetic Construction Set", 2, "Common"],
  ["Puzzle Box (Complex)", 2, "Common"],
  ["Refined Pesh", 2, "Common"],
  ["Rust Scrub", 2, "Uncommon"],
  ["Snake Oil", 2, "Common"],
  ["Waffle Iron (Imprint)", 2, "Common"],
  ["Acid Flask (Lesser)", 3, "Common"],
  ["Alarm Snare", 3, "Common"],
  ["Alchemical Fuse", 3, "Common"],
  ["Alchemist's Fire (Lesser)", 3, "Common"],
  ["Animal Repellent (Minor)", 3, "Common"],
  ["Antidote (Lesser)", 3, "Common"],
  ["Antiplague (Lesser)", 3, "Common"],
  ["Appetizing Flavor Snare", 3, "Rare"],
  ["Aroma Concealer", 3, "Common"],
  ["Arsenic", 3, "Common"],
  ["Bane Ammunition (Lesser)", 3, "Common"],
  ["Battering Snare", 3, "Common"],
  ["Bioluminescence Bomb", 3, "Uncommon"],
  ["Blast Boots (Lesser)", 3, "Uncommon"],
  ["Blasting Stone (Lesser)", 3, "Common"],
  ["Blight Bomb (Lesser)", 3, "Common"],
  ["Blindpepper Tube", 3, "Uncommon"],
  ["Bookthief Brew", 3, "Uncommon"],
  ["Bottled Lightning (Lesser)", 3, "Common"],
  ["Caltrop Snare", 3, "Common"],
  ["Cheetah's Elixir (Lesser)", 3, "Common"],
  ["Chilled Fire Noodles", 3, "Uncommon"],
  ["Choker-Arm Mutagen (Lesser)", 3, "Common"],
  ["Clockwork Goggles", 3, "Uncommon"],
  ["Cryomister (Lesser)", 3, "Uncommon"],
  ["Deadweight Mutagen (Lesser)", 3, "Common"],
  ["Dread Ampoule (Lesser)", 3, "Common"],
  ["Dust Pods", 3, "Uncommon"],
  ["Elemental Ammunition (Lesser)", 3, "Common"],
  ["Elixir of Life (Minor)", 3, "Common"],
  ["Elsie's Excellent Bottled Vim", 3, "Rare"],
  ["Emergency Disguise", 3, "Uncommon"],
  ["Forensic Dye", 3, "Common"],
  ["Frost Vial (Lesser)", 3, "Common"],
  ["Gecko Potion", 3, "Common"],
  ["Ghost Charge (Lesser)", 3, "Common"],
  ["Ghost Ink", 3, "Common"],
  ["Glow Rod", 3, "Common"],
  ["Glue Bomb (Lesser)", 3, "Common"],
  ["Goo Grenade (Lesser)", 3, "Uncommon"],
  ["Grit", 3, "Common"],
  ["Grolna", 3, "Uncommon"],
  ["Hampering Snare", 3, "Common"],
  ["Holy Water", 3, "Common"],
  ["Impact Foam Chassis (Lesser)", 3, "Uncommon"],
  ["Iron Wine", 3, "Uncommon"],
  ["Journeybread", 3, "Uncommon"],
  ["Lady's Blessing Oil", 3, "Common"],
  ["Lastwall Soup", 3, "Uncommon"],
  ["Leaper's Elixir (Lesser)", 3, "Common"],
  ["Manacles (Simple)", 3, "Common"],
  ["Marking Snare", 3, "Common"],
  ["Marvelous Miniature (Ladder)", 3, "Common"],
  ["Merciful Balm", 3, "Common"],
  ["Missive Mint", 3, "Common"],
  ["Mud Bomb (Lesser)", 3, "Uncommon"],
  ["Necrotic Bomb (Lesser)", 3, "Common"],
  ["Nectar of Purification", 3, "Common"],
  ["Pernicious Spore Bomb (Lesser)", 3, "Uncommon"],
  ["Peshspine Grenade (Lesser)", 3, "Uncommon"],
  ["Potion of Emergency Escape", 3, "Common"],
  ["Predator's Claw", 3, "Common"],
  ["Predictable Silver Piece", 3, "Common"],
  ["Ration Tonic", 3, "Common"],
  ["Redpitch Bomb (Lesser)", 3, "Rare"],
  ["Replacement Filter (Level 1)", 3, "Uncommon"],
  ["Runestone", 3, "Common"],
  ["Sack of Rotten Fruit", 3, "Common"],
  ["Sanguine Mutagen (Lesser)", 3, "Common"],
  ["Searing Suture (Lesser)", 3, "Uncommon"],
  ["Self-Immolating Note", 3, "Uncommon"],
  ["Shining Ammunition", 3, "Common"],
  ["Signaling Snare", 3, "Common"],
  ["Silver Tripod", 3, "Common"],
  ["Smoke Ball (Lesser)", 3, "Common"],
  ["Smoke Screen Snare (Lesser)", 3, "Uncommon"],
  ["Spear Frog Poison", 3, "Common"],
  ["Spike Snare", 3, "Common"],
  ["Star Grenade (Lesser)", 3, "Uncommon"],
  ["Steelscour (lesser)", 3, "Uncommon"],
  ["Tallow Bomb (Lesser)", 3, "Uncommon"],
  ["Theatrical Mutagen (Lesser)", 3, "Common"],
  ["Thunderbird Tuft (Lesser)", 3, "Common"],
  ["Thunderstone (Lesser)", 3, "Common"],
  ["Twigjack Sack (Lesser)", 3, "Uncommon"],
  ["Unholy Water", 3, "Common"],
  ["Water Bomb (Lesser)", 3, "Uncommon"],
  ["1st-rank Scroll", 4, "Common"],
  ["Ablative Armor Plating (Lesser)", 4, "Uncommon"],
  ["Ablative Shield Plating (Lesser)", 4, "Uncommon"],
  ["Alicorn Hair", 4, "Common"],
  ["Alignment Ampoule (Lesser)", 4, "Uncommon"],
  ["Animal-Turning Fulu", 4, "Rare"],
  ["Armor Latches", 4, "Common"],
  ["Armor Polishing Kit", 4, "Uncommon"],
  ["Bestial Mutagen (Lesser)", 4, "Common"],
  ["Blood Bomb (Lesser)", 4, "Uncommon"],
  ["Blood Sap", 4, "Common"],
  ["Cognitive Mutagen (Lesser)", 4, "Common"],
  ["Drakeheart Mutagen (Lesser)", 4, "Common"],
  ["Eagle-Eye Elixir (Lesser)", 4, "Common"],
  ["Energy Mutagen (Lesser)", 4, "Common"],
  ["Explosive Mine (Lesser)", 4, "Uncommon"],
  ["Feyfoul (Lesser)", 4, "Rare"],
  ["Firecracker Fulu", 4, "Rare"],
  ["Flare Beacon (Lesser)", 4, "Uncommon"],
  ["Giant Centipede Venom", 4, "Common"],
  ["Glowing Lantern Fruit", 4, "Uncommon"],
  ["Healing Potion (Minor)", 4, "Common"],
  ["Juggernaut Mutagen (Lesser)", 4, "Common"],
  ["Junk Bomb (Lesser)", 4, "Uncommon"],
  ["Numbing Tonic (Minor)", 4, "Common"],
  ["Ogre Spider Filament", 4, "Common"],
  ["Oil of Unlife (Minor)", 4, "Common"],
  ["Poison Barbs Snare", 4, "Common"],
  ["Potency Crystal", 4, "Common"],
  ["Potion of Retaliation (Minor)", 4, "Common"],
  ["Potion of Shared Memories", 4, "Common"],
  ["Pressure Bomb (Lesser)", 4, "Uncommon"],
  ["Prey Mutagen (Lesser)", 4, "Rare"],
  ["Privacy Ward Fulu (Hallway)", 4, "Rare"],
  ["Quicksilver Mutagen (Lesser)", 4, "Common"],
  ["Serene Mutagen (Lesser)", 4, "Common"],
  ["Shielding Salve", 4, "Common"],
  ["Silvertongue Mutagen (Lesser)", 4, "Common"],
  ["Skeptic's Elixir (Lesser)", 4, "Uncommon"],
  ["Skunk Bomb (Lesser)", 4, "Common"],
  ["Sticky Algae Bomb (Lesser)", 4, "Common"],
  ["Sulfur Bomb (Lesser)", 4, "Uncommon"],
  ["Vaccine (Minor)", 4, "Common"],
  ["Vexing Vapor (Lesser)", 4, "Uncommon"],
  ["War Blood Mutagen (Lesser)", 4, "Uncommon"],
  ["Wolf Fang", 4, "Common"],
  ["Wolliped Fleece", 4, "Common"],
  ["Burnished Plating", 5, "Uncommon"],
  ["Cantrip Deck (5-Pack)", 5, "Common"],
  ["Ignitor", 5, "Common"],
  ["Loaded Dice", 5, "Common"],
  ["Mask (Rubber)", 5, "Common"],
  ["Psychopomp Mask", 5, "Uncommon"],
  ["Subtle Armor", 5, "Uncommon"],
  ["Throwing Shield", 5, "Uncommon"],
  ["Twining Chains", 5, "Uncommon"],
  ["Waterproof Journal", 5, "Uncommon"],
  ["Dwarven Daisy (Lesser)", 6, "Uncommon"],
  ["Weapon Harness", 6, "Uncommon"],
  ["Sukgung", 7, "Common"],
  ["Traveler's Cloak", 7, "Uncommon"],
  ["Rhythm Bone", 8, "Uncommon"],
  ["Stiletto Pen", 8, "Uncommon"],
  ["Aeon Stone (Consumed)", 9, "Uncommon"],
  ["Barricade Buster", 9, "Uncommon"],
  ["Alchemical Gauntlet", 10, "Common"],
  ["Axe Musket", 10, "Uncommon"],
  ["Big Boom Gun", 10, "Uncommon"],
  ["Bioluminescent Stripes", 10, "Common"],
  ["Communication Bangle", 10, "Uncommon"],
  ["Dragon's Crest", 10, "Uncommon"],
  ["Dwarven Scattergun", 10, "Uncommon"],
  ["Explosive Dogslicer", 10, "Uncommon"],
  ["Floating Tent (Pup)", 10, "Common"],
  ["Ganjay Book", 10, "Uncommon"],
  ["Genealogy Mask", 10, "Uncommon"],
  ["Glittering Scarab", 10, "Uncommon"],
  ["Gnome Amalgam Musket", 10, "Uncommon"],
  ["Hellknight Breastplate", 10, "Uncommon"],
  ["Injection Reservoir", 10, "Common"],
  ["Mantis Shell", 10, "Uncommon"],
  ["Mask (Plague)", 10, "Common"],
  ["Mechanical Torch", 10, "Common"],
  ["Phalanx Piercer", 10, "Common"],
  ["Poison Ring", 10, "Uncommon"],
  ["Polytool", 10, "Uncommon"],
  ["Purifying Spoon (Teaspoon)", 10, "Common"],
  ["Repeating Hand Crossbow", 10, "Uncommon"],
  ["Sibling's Coin", 10, "Uncommon"],
  ["Spoon Gun", 10, "Uncommon"],
  ["Timepiece (Desktop Clock)", 10, "Uncommon"],
  ["Weapon Siphon", 10, "Common"],
  ["Double-barreled Musket", 11, "Uncommon"],
  ["Jezail", 11, "Uncommon"],
  ["Candlecap", 12, "Common"],
  ["Dueling Pistol", 12, "Uncommon"],
  ["Scrollstaff", 12, "Uncommon"],
  ["Slippery Ribbon", 12, "Uncommon"],
  ["Switchscythe", 12, "Uncommon"],
  ["Three Peaked Tree", 12, "Uncommon"],
  ["Walking Cauldron", 12, "Common"],
  ["Gun Sword", 13, "Uncommon"],
  ["Hammer Gun", 13, "Uncommon"],
  ["Splint Mail", 13, "Common"],
  ["Composite Shortbow", 14, "Common"],
  ["Bristling Spines (Lesser)", 15, "Common"],
  ["Clockwork Bookshelf", 15, "Uncommon"],
  ["Clockwork Megaphone", 15, "Uncommon"],
  ["Deployable Cover", 15, "Uncommon"],
  ["Everlight Crystal", 15, "Common"],
  ["Grappling Gun (Clockwork)", 15, "Uncommon"],
  ["Mudlily", 15, "Uncommon"],
  ["Repeating Crossbow", 15, "Uncommon"],
  ["Ring of Discretion", 15, "Common"],
  ["Net Launcher", 16, "Rare"],
  ["Slide Pistol", 16, "Uncommon"],
  ["Backpack Ballista", 18, "Uncommon"],
  ["Blade Launcher", 18, "Uncommon"],
  ["Half Plate", 18, "Common"],
  ["Backpack Catapult", 20, "Uncommon"],
  ["Bomb Launcher", 20, "Uncommon"],
  ["Cantrip Deck (Full Pack)", 20, "Common"],
  ["Cloak of Feline Rest", 20, "Common"],
  ["Composite Longbow", 20, "Common"],
  ["Fortress Shield", 20, "Common"],
  ["Hellknight Half Plate", 20, "Uncommon"],
  ["Purifying Spoon (Tablespoon)", 20, "Common"],
  ["Repeating Heavy Crossbow", 20, "Uncommon"],
  ["Ring of Sigils", 20, "Common"],
  ["Shobhad Longrifle", 20, "Rare"],
  ["Stalk Goggles", 20, "Rare"],
  ["Swarmsuit", 20, "Common"],
  ["Versatile Tinderbox", 20, "Common"]
]

const itens2 = [
  ["Adaptive Cogwheel", 5, "Common"],
  ["Aromatic Ammunition", 5, "Common"],
  ["Belladonna", 5, "Common"],
  ["Black Powder (Horn)", 5, "Uncommon"],
  ["Black Smear Poison", 5, "Uncommon"],
  ["Bottled Catharsis (Minor)", 5, "Common"],
  ["Boulderhead Bock", 5, "Uncommon"],
  ["Bubbling Scale", 5, "Uncommon"],
  ["Clockwork Monkey", 5, "Uncommon"],
  ["Cooperative Waffles", 5, "Common"],
  ["Dragon's Blood Pudding (Lesser)", 5, "Uncommon"],
  ["Emetic Paste (Lesser)", 5, "Common"],
  ["Everair Mask (Lesser)", 5, "Common"],
  ["False Flayleaf", 5, "Common"],
  ["Flare Snare", 5, "Common"],
  ["Instant Spy", 5, "Uncommon"],
  ["Kirin Echo Chime", 5, "Common"],
  ["Life Shot (Minor)", 5, "Common"],
  ["Lovers' Ink", 5, "Rare"],
  ["Mender's Soup", 5, "Common"],
  ["Moonlit Ink", 5, "Uncommon"],
  ["Oil of Skating", 5, "Common"],
  ["Quickmelt Slick (Lesser)", 5, "Uncommon"],
  ["Sinew-Shock Serum (Lesser)", 5, "Common"],
  ["Smoke Fan", 5, "Uncommon"],
  ["Spirit Trap", 5, "Uncommon"],
  ["Surging Serum (Minor)", 5, "Common"],
  ["Toy Carriage (Windup)", 5, "Common"],
  ["Writ of Authenticity", 5, "Uncommon"],
  ["Anticorrosion Oil", 6, "Common"],
  ["Antivenom Potion", 6, "Common"],
  ["Black Adder Venom", 6, "Common"],
  ["Bloodhound Mask (Lesser)", 6, "Common"],
  ["Darkvision Elixir (Lesser)", 6, "Common"],
  ["Deadweight Snare", 6, "Uncommon"],
  ["Ember Dust", 6, "Uncommon"],
  ["Expulsion Snare", 6, "Rare"],
  ["Feather Token (Holly Bush)", 6, "Common"],
  ["Hunter's Bane", 6, "Common"],
  ["Infiltrator's Elixir", 6, "Common"],
  ["Jade Cat", 6, "Common"],
  ["Looter's Lethargy", 6, "Uncommon"],
  ["Lover's Knot", 6, "Uncommon"],
  ["Monkey Pin", 6, "Common"],
  ["Moon Radish Soup", 6, "Uncommon"],
  ["Noisemaker Snare", 6, "Uncommon"],
  ["Oil of Weightlessness", 6, "Common"],
  ["Origin Unguent", 6, "Common"],
  ["Silver Salve", 6, "Common"],
  ["Spring-Loaded Net Launcher", 6, "Uncommon"],
  ["Static Snare", 6, "Uncommon"],
  ["Tatzlwyrm's Gasp", 6, "Common"],
  ["Thunder Snare", 6, "Common"],
  ["Toad Tears", 6, "Common"],
  ["Tripline Arrow", 6, "Rare"],
  ["Wind-Up Cart", 6, "Uncommon"],
  ["Winterstep Elixir (Minor)", 6, "Uncommon"],
  ["Antler Arrow", 7, "Common"],
  ["Blaze", 7, "Uncommon"],
  ["Bottled Sunlight (Lesser)", 7, "Common"],
  ["Bravo's Brew (Lesser)", 7, "Common"],
  ["Bronze Bull Pendant", 7, "Common"],
  ["Cat's Eye Elixir", 7, "Common"],
  ["Comprehension Elixir (Lesser)", 7, "Common"],
  ["Crying Angel Pendant", 7, "Common"],
  ["Dark Pepper Powder", 7, "Uncommon"],
  ["Effervescent Ampoule", 7, "Common"],
  ["Lethargy Poison", 7, "Uncommon"],
  ["Mesmerizing Opal", 7, "Common"],
  ["Moonlit Spellgun (Minor)", 7, "Common"],
  ["Oil of Potency", 7, "Common"],
  ["Onyx Panther", 7, "Common"],
  ["Ooze Ammunition (Lesser)", 7, "Common"],
  ["Red-Rib Gill Mask (Lesser)", 7, "Rare"],
  ["Sanitizing Pin", 7, "Uncommon"],
  ["Savior Spike", 7, "Common"],
  ["Sneezing Powder", 7, "Uncommon"],
  ["Soothing Tonic (Lesser)", 7, "Common"],
  ["Spun Cloud (White)", 7, "Common"],
  ["Traveler's Fulu", 7, "Rare"],
  ["Yellow Musk Vial", 7, "Uncommon"],
  ["Cauterizing Torch", 10, "Uncommon"],
  ["Cold Iron Chunk", 10, "Common"],
  ["Exquisite Surprise Doll", 10, "Common"],
  ["Parade Armor", 10, "Uncommon"],
  ["Silver Chunk", 10, "Common"],
  ["Cold Iron Object (Low-Grade)", 20, "Common"],
  ["Gunner's Saddle", 20, "Uncommon"],
  ["Portable Animal Blind", 20, "Common"],
  ["Silver Object (Low-Grade)", 20, "Common"],
  ["Barding (Heavy; Small or Medium)", 25, "Common"],
  ["Book of Translation (Standard)", 25, "Uncommon"],
  ["Bottomless Stein", 25, "Uncommon"],
  ["Dweomerweave Robe", 25, "Uncommon"],
  ["Experimental Clothing", 25, "Uncommon"],
  ["Flask of Fellowship", 25, "Common"],
  ["Floating Tent (Four-Person)", 25, "Common"],
  ["Legerdemain Handkerchief", 25, "Common"],
  ["Necklace of Knives", 25, "Uncommon"],
  ["Periscope", 25, "Common"],
  ["Pocket Watch", 25, "Uncommon"],
  ["Soulspeaker", 25, "Rare"],
  ["Wrist Grappler", 25, "Uncommon"],
  ["Wayfinder", 28, "Uncommon"],
  ["Archaic Wayfinder", 30, "Uncommon"],
  ["Astrolabe (Standard)", 30, "Uncommon"],
  ["Brooch of Shielding", 30, "Uncommon"],
  ["Cold Iron Buckler (Low-Grade)", 30, "Common"],
  ["Day Goggles", 30, "Uncommon"],
  ["Fanged", 30, "Uncommon"],
  ["Full Plate", 30, "Common"],
  ["Goz Mask", 30, "Common"],
  ["Holy Steam Ball", 30, "Uncommon"],
  ["Jack's Tattered Cape", 30, "Rare"],
  ["Masquerade Scarf", 30, "Common"],
  ["Paper Shredder", 30, "Uncommon"],
  ["Pathfinder's Coin", 30, "Uncommon"],
  ["Polar Travel Kit", 30, "Common"],
  ["Quick Wig", 30, "Uncommon"],
  ["Silver Buckler (Low-Grade)", 30, "Common"],
  ["Skittering Mask", 30, "Common"],
  ["Steadyfoot Tassel", 30, "Uncommon"],
  ["Stone of Encouragement", 30, "Uncommon"],
  ["Sturdy Satchel", 30, "Uncommon"],
  ["Fortress Plate", 32, "Common"],
  ["Purifying Spoon (Ladle)", 32, "Common"],
  ["Pyrite Rat", 32, "Common"],
  ["Bastion Plate", 33, "Common"],
  ["Cold Iron Shield (Low-Grade)", 34, "Common"],
  ["Silver Shield (Low-Grade)", 34, "Common"],
  ["Wondrous Figurine (Onyx Dog)", 34, "Common"],
  ["Alchemist's Flamethrower", 35, "Rare"],
  ["Deployable Cover (Ballistic Cover)", 35, "Uncommon"],
  ["Furnace of Endings (Lesser)", 35, "Uncommon"],
  ["Glamorous Buckler", 35, "Common"],
  ["Gray Maiden Plate", 35, "Common"],
  ["Handwraps of Mighty Blows (+1)", 35, "Common"],
  ["Hellknight Plate", 35, "Uncommon"],
  ["Magic Weapon (+1)", 35, "Common"],
  ["O-Yoroi", 35, "Common"],
  ["Weapon Potency (+1)", 35, "Common"],
  ["Axolotl", 40, "Common"],
  ["Cold Iron Weapon (Low-Grade)", 40, "Common"],
  ["Mycoweave Shield (Lesser)", 40, "Uncommon"],
  ["Silver Weapon (Low-Grade)", 40, "Common"],
  ["Tent (Pavilion)", 40, "Common"],
  ["Barding (Heavy; Large)", 50, "Common"],
  ["Cradle Minder", 50, "Common"],
  ["Dreamweb Bolt", 50, "Rare"],
  ["Cold Iron Ingot", 100, "Common"],
  ["Silver Ingot", 100, "Common"],
  ["Hat of Disagreeable Disguise", 0, "Rare"],
  ["Luckless Dice", 0, "Rare"],
  ["Stone of Weight", 0, "Rare"]
]

const itens3 = [
  ["Thieves' Toolkit (Infiltrator Picks)", 3, "Common"],
  ["Impossible Cake", 5, "Uncommon"],
  ["Scholarly Journal", 6, "Uncommon"],
  ["Blue Dragonfly Poison", 7, "Uncommon"],
  ["Conrasu Coin (Arbiter)", 7, "Uncommon"],
  ["Clockwork Chirper", 8, "Uncommon"],
  ["Colorful Coating (Blue)", 8, "Common"],
  ["Colorful Coating (Yellow)", 8, "Common"],
  ["Elixir of Gender Transformation (Moderate)", 8, "Common"],
  ["Feather Step Stone", 8, "Common"],
  ["Feather Token (Bird)", 8, "Common"],
  ["Feather Token (Puddle)", 8, "Common"],
  ["Neophyte's Fipple", 8, "Common"],
  ["Oil of Ownership (Lesser)", 8, "Common"],
  ["Parchment of Secrets", 8, "Uncommon"],
  ["Serpent Oil (Lesser)", 8, "Common"],
  ["Setup Snare", 8, "Uncommon"],
  ["Vermin Repellent Agent (Lesser)", 8, "Uncommon"],
  ["Blood Booster (Lesser)", 9, "Common"],
  ["Diplomat's Charcuterie", 9, "Common"],
  ["Drowsy Sun Eye Drops", 9, "Common"],
  ["Grasping Tree", 9, "Uncommon"],
  ["Merciful Charm", 9, "Uncommon"],
  ["Oil of Mending", 9, "Common"],
  ["Olfactory Obfuscator", 9, "Common"],
  ["Ranging Shot", 9, "Common"],
  ["Revealing Mist (Lesser)", 9, "Common"],
  ["Rock Ripper Snare", 9, "Uncommon"],
  ["Snapleaf", 9, "Common"],
  ["Steelscour (moderate)", 9, "Uncommon"],
  ["Toothwort Extract", 9, "Common"],
  ["Torrent Snare", 9, "Uncommon"],
  ["Trustworthy Round", 9, "Common"],
  ["Acid Flask (Moderate)", 10, "Common"],
  ["Alchemist's Fire (Moderate)", 10, "Common"],
  ["Alloy Orb (Low-Grade)", 10, "Common"],
  ["Auric Noodles", 10, "Common"],
  ["Beacon Shot", 10, "Common"],
  ["Blasting Stone (Moderate)", 10, "Common"],
  ["Blight Bomb (Moderate)", 10, "Common"],
  ["Blindpepper Bolt", 10, "Uncommon"],
  ["Bottled Lightning (Moderate)", 10, "Common"],
  ["Breech Ejectors", 10, "Uncommon"],
  ["Camouflage Dye (Lesser)", 10, "Common"],
  ["Camouflage Suit", 10, "Uncommon"],
  ["Candle of Inflamed Passions", 10, "Common"],
  ["Captivating Rosebud", 10, "Uncommon"],
  ["Chaos Falcon Feather", 10, "Common"],
  ["Cold Iron Blanch (Lesser)", 10, "Uncommon"],
  ["Colorful Coating (Green)", 10, "Common"],
  ["Colorful Coating (Indigo)", 10, "Common"],
  ["Colorful Coating (Red)", 10, "Common"],
  ["Covenant Tea", 10, "Uncommon"],
  ["Cytillesh Oil", 10, "Common"],
  ["Disrupting Oil", 10, "Uncommon"],
  ["Dread Ampoule (Moderate)", 10, "Common"],
  ["Fire Box", 10, "Uncommon"],
  ["Forgetful Drops", 10, "Uncommon"],
  ["Frost Vial (Moderate)", 10, "Common"],
  ["Fulu of Fire Suppression", 10, "Common"],
  ["Fulu of Flood Suppression", 10, "Common"],
  ["Ghost Charge (Moderate)", 10, "Common"],
  ["Glue Bomb (Moderate)", 10, "Common"],
  ["Goo Grenade (Moderate)", 10, "Uncommon"],
  ["Graveroot", 10, "Common"],
  ["Hoof Stakes Snare", 10, "Uncommon"],
  ["Marvelous Miniature (Chest)", 10, "Common"],
  ["Matchmaker Fulu", 10, "Common"],
  ["Mud Bomb (Moderate)", 10, "Uncommon"],
  ["Necrotic Bomb (Moderate)", 10, "Common"],
  ["Pernicious Spore Bomb (Moderate)", 10, "Uncommon"],
  ["Peshspine Grenade (Moderate)", 10, "Uncommon"],
  ["Psychic Warding Bracelet", 10, "Common"],
  ["Puzzle Box (Challenging)", 10, "Common"],
  ["Quickpatch Glue", 10, "Uncommon"],
  ["Recovery Bladder", 10, "Rare"],
  ["Redpitch Bomb (Moderate)", 10, "Rare"],
  ["Seventh Prism (Triangular)", 10, "Common"],
  ["Shiver", 10, "Common"],
  ["Silversoul Bomb", 10, "Rare"],
  ["Slumber Arrow", 10, "Common"],
  ["Soothing Scents", 10, "Common"],
  ["Spirit-Sealing Fulu", 10, "Common"],
  ["Sprite Apple (Golden)", 10, "Common"],
  ["Star Grenade (Moderate)", 10, "Uncommon"],
  ["Stumbling Fulu", 10, "Common"],
  ["Survey Map", 10, "Uncommon"],
  ["Tallow Bomb (Moderate)", 10, "Uncommon"],
  ["Thumper Snare", 10, "Rare"],
  ["Thunderstone (Moderate)", 10, "Common"],
  ["Toadskin Salve", 10, "Uncommon"],
  ["Tracker's Stew", 10, "Common"],
  ["Twigjack Sack (Moderate)", 10, "Uncommon"],
  ["Venomous Cure Fulu", 10, "Common"],
  ["Vine Arrow", 10, "Common"],
  ["Water Bomb (Moderate)", 10, "Uncommon"],
  ["Waterproofing Wax", 10, "Common"],
  ["Artevil Suspension", 11, "Common"],
  ["Blast Boots (Moderate)", 11, "Uncommon"],
  ["Blood Bomb (Moderate)", 11, "Uncommon"],
  ["Bralani Breath", 11, "Common"],
  ["Metalmist Sphere (Lesser)", 11, "Uncommon"],
  ["Potion of Water Breathing", 11, "Common"],
  ["Sleep Arrow", 11, "Common"],
  ["Witch's Finger", 11, "Common"],
  ["2nd-rank Scroll", 12, "Common"],
  ["Ablative Armor Plating (Moderate)", 12, "Uncommon"],
  ["Ablative Shield Plating (Moderate)", 12, "Uncommon"],
  ["Alignment Ampoule (Moderate)", 12, "Uncommon"],
  ["Aurifying Salts", 12, "Uncommon"],
  ["Bane Oil", 12, "Uncommon"],
  ["Bestial Mutagen (Moderate)", 12, "Common"],
  ["Bottled Night", 12, "Uncommon"],
  ["Choker-Arm Mutagen (Moderate)", 12, "Common"],
  ["Clinging Bubbles (Lesser)", 12, "Common"],
  ["Cognitive Mutagen (Moderate)", 12, "Common"],
  ["Colorful Coating (Orange)", 12, "Common"],
  ["Deadweight Mutagen (Moderate)", 12, "Common"],
  ["Demolition Fulu (Lesser)", 12, "Common"],
  ["Detonating Gears Snare", 12, "Common"],
  ["Draft of Stellar Radiance", 12, "Rare"],
  ["Drakeheart Mutagen (Moderate)", 12, "Common"],
  ["Dream Pollen Snare", 12, "Uncommon"],
  ["Ectoplasmic Tracer", 12, "Common"],
  ["Energy Mutagen (Moderate)", 12, "Common"],
  ["Etheric Essence Disruptor (Lesser)", 12, "Uncommon"],
  ["Healing Potion (Lesser)", 12, "Common"],
  ["Hippogriff Feather", 12, "Common"],
  ["Indomitable Keepsake", 12, "Common"],
  ["Juggernaut Mutagen (Moderate)", 12, "Common"],
  ["Junk Bomb (Moderate)", 12, "Uncommon"],
  ["Life-Boosting Oil (Lesser)", 12, "Uncommon"],
  ["Lodestone Pellet", 12, "Uncommon"],
  ["Longnight Tea", 12, "Uncommon"],
  ["Material Essence Disruptor (Lesser)", 12, "Uncommon"],
  ["Matsuki's Medicinal Wine", 12, "Rare"],
  ["Oil of Unlife (Lesser)", 12, "Common"],
  ["Periscopic Viewfinder", 12, "Rare"],
  ["Potion of Retaliation (Lesser)", 12, "Common"],
  ["Pressure Bomb (Moderate)", 12, "Uncommon"],
  ["Prey Mutagen (Moderate)", 12, "Rare"],
  ["Putrid Sack of Rotting Fruit", 12, "Common"],
  ["Quicksilver Mutagen (Moderate)", 12, "Common"],
  ["Retrieval Prism", 12, "Common"],
  ["Sanguine Mutagen (Moderate)", 12, "Common"],
  ["Seeking Bracelets", 12, "Uncommon"],
  ["Serene Mutagen (Moderate)", 12, "Common"],
  ["Silvertongue Mutagen (Moderate)", 12, "Common"],
  ["Skunk Bomb (Moderate)", 12, "Common"],
  ["Spellstrike Ammunition (Type I)", 12, "Common"],
  ["Spiderfoot Brew (Lesser)", 12, "Common"],
  ["Sticky Algae Bomb (Moderate)", 12, "Common"],
  ["Sulfur Bomb (Moderate)", 12, "Uncommon"],
  ["Swamp Lily Quilt", 12, "Rare"],
  ["Tailor's Boll", 12, "Common"],
  ["Theatrical Mutagen (Moderate)", 12, "Common"],
  ["Torrent Spellgun (Lesser)", 12, "Common"],
  ["Vaccine (Lesser)", 12, "Common"],
  ["Vexing Vapor (Moderate)", 12, "Uncommon"],
  ["Violet Venom", 12, "Uncommon"],
  ["War Blood Mutagen (Moderate)", 12, "Uncommon"],
  ["Wemmuth Trinket", 12, "Common"],
  ["Knight's Tabard", 15, "Uncommon"],
  ["Lock (Average)", 15, "Common"],
  ["Scroll Belt", 15, "Uncommon"],
  ["Dwarven Daisy (Moderate)", 18, "Uncommon"],
  ["Compass (Lensatic)", 20, "Common"],
  ["Crowbar (Levered)", 20, "Common"],
  ["Everyneed Pack", 20, "Uncommon"],
  ["Fishing Tackle (Professional)", 20, "Common"],
  ["Manacles (Average)", 20, "Common"],
  ["Portable Ram", 20, "Common"],
  ["Recording Rod (Basic)", 20, "Uncommon"],
  ["Smoked Goggles", 20, "Common"],
  ["Concealed Holster", 25, "Uncommon"],
  ["Concealed Sheath", 25, "Common"],
  ["Detective's Kit", 25, "Common"],
  ["Portable Altar", 25, "Uncommon"],
  ["Repair Toolkit (Superb)", 25, "Common"],
  ["Fingerprinting Kit", 30, "Uncommon"],
  ["Handcuffs (Average)", 30, "Uncommon"],
  ["Rappelling Kit", 30, "Uncommon"],
  ["Scholarly Journal (Compendium)", 30, "Uncommon"],
  ["Sisterstone Object (Low-Grade)", 30, "Rare"],
  ["Climbing Kit (Extreme)", 40, "Common"],
  ["Disguise Kit (Elite)", 40, "Common"],
  ["Magnifying Glass", 40, "Common"],
  ["Vestige Lenses", 40, "Rare"],
  ["Wrist Grappler (Clockwork)", 40, "Uncommon"],
  ["Cartographer's Kit", 42, "Uncommon"],
  ["Anylength Rope (Lesser)", 45, "Common"],
  ["Backfire Mantle", 45, "Common"],
  ["Codebreaker's Parchment", 45, "Common"],
  ["Coin of Comfort", 45, "Uncommon"],
  ["Corpse Compass", 45, "Uncommon"],
  ["Electrocable", 45, "Rare"],
  ["Manacles of Persuasion", 45, "Uncommon"],
  ["Preserving", 45, "Common"],
  ["Rope of Climbing (Lesser)", 45, "Common"],
  ["Twisting Twine (Lesser)", 45, "Common"],
  ["Whip Tail", 45, "Common"],
  ["Wig of Holding", 45, "Uncommon"],
  ["Abadar's Flawless Scale", 50, "Uncommon"],
  ["Aeon Stone (Dusty Rose Prism)", 50, "Uncommon"],
  ["Aeon Stone (Polished Pebble)", 50, "Uncommon"],
  ["Armory Bracelet (Minor)", 50, "Common"],
  ["Artisan's Toolkit (Sterling)", 50, "Common"],
  ["Astrolabe (Mariner's)", 50, "Uncommon"],
  ["Authorized", 50, "Common"],
  ["Broken Tusk Pendant", 50, "Rare"],
  ["Charlatan's Gloves", 50, "Common"],
  ["Clockwork Box Packer", 50, "Uncommon"],
  ["Crushing", 50, "Uncommon"],
  ["Doubling Rings", 50, "Common"],
  ["Fashionable Wayfinder", 50, "Uncommon"],
  ["Fighter's Fork", 50, "Common"],
  ["Flash Beetle Lantern", 50, "Uncommon"],
  ["Giant Catch Pole", 50, "Uncommon"],
  ["Gliding Membranes (Lesser)", 50, "Common"],
  ["Hag Eye", 50, "Rare"],
  ["Healer's Toolkit (Expanded)", 50, "Common"],
  ["Hoax-Hunter's Kit", 50, "Uncommon"],
  ["Mage's Hat", 50, "Common"],
  ["Magnet Coin", 50, "Uncommon"],
  ["Menacing", 50, "Common"],
  ["Musical Instrument (Virtuoso Handheld)", 50, "Common"],
  ["Parchment of Direct Message", 50, "Uncommon"],
  ["Persona Mask", 50, "Common"],
  ["Portable Weapon Mount (Tripod, Shielded)", 50, "Uncommon"],
  ["Presentable", 50, "Uncommon"],
  ["Sharpened Canines", 50, "Common"],
  ["Skinsaw Mask", 50, "Uncommon"],
  ["Slashing Claws", 50, "Common"],
  ["Survey Map (Atlas)", 50, "Uncommon"],
  ["Tanglefoot Extruder", 50, "Common"],
  ["Thieves' Toolkit (Infiltrator)", 50, "Common"],
  ["Timepiece (Grand Clock)", 50, "Uncommon"],
  ["Underwater", 50, "Common"],
  ["Wardrobe Stone (Lesser)", 50, "Uncommon"],
  ["Wind-up Wings (Flutterback)", 50, "Rare"],
  ["Wrenchgear", 50, "Uncommon"],
  ["Blazons of Shared Power", 52, "Common"],
  ["Bracers of Missile Deflection", 52, "Common"],
  ["Immaculate Holsters", 52, "Uncommon"],
  ["Kin-Warding", 52, "Uncommon"],
  ["Piercing Horn", 52, "Common"],
  ["Alchemist's Lab (Expanded)", 55, "Common"],
  ["Bullhook", 55, "Uncommon"],
  ["Clothing (High-Fashion Fine)", 55, "Common"],
  ["Flaming Star", 55, "Common"],
  ["Golden Legion Epaulet", 55, "Uncommon"],
  ["Grim Sandglass", 55, "Common"],
  ["Keymaking Tools", 55, "Common"],
  ["Mirror Robe", 55, "Uncommon"],
  ["Perfect Droplet", 55, "Common"],
  ["Polished Demon Horn", 55, "Uncommon"],
  ["Returning", 55, "Common"],
  ["Rime Crystal", 55, "Common"],
  ["Shining Symbol", 55, "Common"],
  ["Snare Kit (Specialist)", 55, "Common"],
  ["Spry Sinews (Lesser)", 55, "Common"],
  ["Thurible of Revelation (Lesser)", 55, "Common"],
  ["Venom Glands", 55, "Common"],
  ["Wordreaper", 55, "Uncommon"],
  ["Channel Protection Amulet", 56, "Uncommon"],
  ["Sapling Shield (Minor)", 57, "Common"],
  ["Bracelet of Dashing", 58, "Common"],
  ["Aeon Stone (Pearly White Spindle)", 60, "Uncommon"],
  ["Aerial Cloak", 60, "Common"],
  ["Battle Medic's Baton", 60, "Common"],
  ["Bristling Spines (Moderate)", 60, "Common"],
  ["Called (Accessory Rune)", 60, "Uncommon"],
  ["Cloak of Gnawing Leaves", 60, "Rare"],
  ["Coyote Cloak", 60, "Common"],
  ["Crafter's Eyepiece", 60, "Common"],
  ["Cultist Cowl", 60, "Uncommon"],
  ["Dancing Scarf", 60, "Common"],
  ["Dawnlight", 60, "Uncommon"],
  ["Gate Attenuator", 60, "Common"],
  ["Ghast Stiletto", 60, "Common"],
  ["Glasses of Sociability", 60, "Common"],
  ["Gunner's Bandolier", 60, "Uncommon"],
  ["Hunter's Bow", 60, "Common"],
  ["Jolt Coil", 60, "Common"],
  ["Lady's Chalice", 60, "Uncommon"],
  ["Little Love", 60, "Rare"],
  ["Maestro's Instrument (Lesser)", 60, "Common"],
  ["Magic Wand (1st-rank Spell)", 60, "Common"],
  ["Palm Crossbow", 60, "Rare"],
  ["Pendant of the Occult", 60, "Common"],
  ["Pickled Demon Tongue", 60, "Uncommon"],
  ["Raven Band", 60, "Uncommon"],
  ["Retribution Axe", 60, "Common"],
  ["Ring of Torag", 60, "Rare"],
  ["Secret-Keeper's Mask (Blackfingers)", 60, "Rare"],
  ["Secret-Keeper's Mask (Reaper of Reputation)", 60, "Rare"],
  ["Smoke Veil", 60, "Common"],
  ["Smoking Sword", 60, "Common"],
  ["Snagging", 60, "Uncommon"],
  ["Soft-Landing", 60, "Uncommon"],
  ["Staff of Air", 60, "Common"],
  ["Staff of Earth", 60, "Common"],
  ["Staff of Fire", 60, "Common"],
  ["Staff of Water", 60, "Common"],
  ["Stalk Goggles (Greater)", 60, "Rare"],
  ["Storm Hammer", 60, "Common"],
  ["Thrower's Bandolier", 60, "Common"],
  ["Tracker's Goggles", 60, "Common"],
  ["Trinity Geode", 60, "Common"],
  ["Unexceptional", 60, "Uncommon"],
  ["Ventriloquist's Ring", 60, "Common"],
  ["Magnifying Scope", 70, "Common"],
  ["Sisterstone Weapon (Low-Grade)", 70, "Rare"],
  ["Sparkblade", 70, "Common"],
  ["Alpaca", 75, "Common"],
  ["High-Contrast Goggles", 80, "Uncommon"],
  ["Blood Sight Elixir (Lesser)", 100, "Uncommon"],
  ["Diving Suit", 100, "Common"],
  ["Atmospheric Breathing Suit", 100, "Common"],
  ["Musical Instrument (Virtuoso Heavy)", 100, "Common"],
  ["Sambuca", 120, "Rare"],
  ["Ring of Observation (Lesser)", 125, "Uncommon"],
  ["Gaffe Glasses", 0, "Rare"],
  ["Heckling Tools", 0, "Rare"],
  ["Sluggish Bracelet", 0, "Rare"]
]

const itens4 = [
  ("Darkvision Elixir (Moderate)", 11, "Common"),
  ("Yarrow-Root Bandage", 12, "Common"),
  ("Dragon Turtle Scale", 13, "Common"),
  ("Dreamtime Tea", 13, "Common"),
  ("Explosive Missive", 13, "Common"),
  ("Fortifying Pebble", 13, "Uncommon"),
  ("Marvelous Miniature (Horse)", 13, "Common"),
  ("Phantom Roll", 13, "Common"),
  ("Quickmelt Slick (Moderate)", 13, "Uncommon"),
  ("Stone Fist Elixir", 13, "Common"),
  ("Bomber's Eye Elixir (Lesser)", 14, "Common"),
  ("Cinnamon Seers", 14, "Common"),
  ("Saboteur's Friend", 14, "Common"),
  ("Timeless Salts", 14, "Common"),
  ("Acid Spitter", 15, "Uncommon"),
  ("Animal Nip (Lesser)", 15, "Common"),
  ("Animal Repellent (Lesser)", 15, "Common"),
  ("Biting Snare", 15, "Common"),
  ("Blessed Ampoule", 15, "Uncommon"),
  ("Bottled Catharsis (Lesser)", 15, "Common"),
  ("Camp Shroud (Minor)", 15, "Uncommon"),
  ("Chilled Fire Noodles (Greater)", 15, "Uncommon"),
  ("Chimera Thread", 15, "Common"),
  ("Climbing Bolt", 15, "Common"),
  ("Clockwork Goggles (Greater)", 15, "Uncommon"),
  ("Colorful Coating (Violet)", 15, "Common"),
  ("Cooling Elixir (Lesser)", 15, "Common"),
  ("Dazzling Rosary", 15, "Common"),
  ("Deteriorating Dust", 15, "Uncommon"),
  ("Exsanguinating Ammunition", 15, "Common"),
  ("Fang Snare", 15, "Uncommon"),
  ("Feather Token (Fan)", 15, "Common"),
  ("Fire-Douse Snare", 15, "Rare"),
  ("Fury Cocktail (Lesser)", 15, "Common"),
  ("Harpoon Bolt", 15, "Uncommon"),
  ("Hobbling Snare", 15, "Uncommon"),
  ("Impact Foam Chassis (Moderate)", 15, "Uncommon"),
  ("Irondust Stew", 15, "Uncommon"),
  ("Irritating Thorn Snare", 15, "Uncommon"),
  ("Journeybread (Power)", 15, "Uncommon"),
  ("Leadenleg", 15, "Common"),
  ("Lion Badge", 15, "Uncommon"),
  ("Magical Lock Fulu", 15, "Common"),
  ("Oak Potion", 15, "Common"),
  ("Oxygen Ooze", 15, "Uncommon"),
  ("Rainbow Vinegar", 15, "Uncommon"),
  ("Rattling Bolt", 15, "Uncommon"),
  ("Sentry Fulu", 15, "Common"),
  ("Shrinking Potion", 15, "Common"),
  ("Sinew-Shock Serum (Moderate)", 15, "Common"),
  ("Stalker Bane Snare", 15, "Uncommon"),
  ("Surging Serum (Lesser)", 15, "Common"),
  ("Tar Rocket Snare", 15, "Uncommon"),
  ("Trip Snare", 15, "Common"),
  ("Void Salts", 15, "Uncommon"),
  ("Warning Snare", 15, "Common"),
  ("Witchwarg Elixir (Lesser)", 15, "Common"),
  ("Chameleon Suit", 16, "Uncommon"),
  ("Crystal Shards (Moderate)", 16, "Common"),
  ("Fearflower Nectar", 16, "Common"),
  ("Glue Bullet", 16, "Uncommon"),
  ("Sniper's Bead", 16, "Common"),
  ("Sprite Apple (Pink)", 16, "Common"),
  ("Capsaicin Tonic", 17, "Uncommon"),
  ("Cloud Buns", 17, "Uncommon"),
  ("Sure-Step Potion", 17, "Common"),
  ("Viper Arrow", 17, "Common"),
  ("Anointing Oil", 18, "Uncommon"),
  ("Boom Snare", 18, "Uncommon"),
  ("Brightshade", 18, "Common"),
  ("Dischoran Rubble", 18, "Common"),
  ("Ghost Oil", 18, "Common"),
  ("Glittering Snare", 18, "Uncommon"),
  ("Grave Token", 18, "Uncommon"),
  ("Messenger Missive", 18, "Common"),
  ("Mistform Elixir (Lesser)", 18, "Common"),
  ("Aether Marble (Lesser)", 19, "Uncommon"),
  ("Admonishing Band", 20, "Common"),
  ("Applereed Mutagen (Lesser)", 20, "Rare"),
  ("Bloodhammer Reserve", 20, "Uncommon"),
  ("Bloodseeker Beak", 20, "Common"),
  ("Bottled Omen", 20, "Rare"),
  ("Bottled Sunlight (Moderate)", 20, "Common"),
  ("Dragonbone Arrowhead", 20, "Common"),
  ("Energized Cartridge", 20, "Common"),
  ("Energizing Tea", 20, "Uncommon"),
  ("Essence of Mandragora", 20, "Common"),
  ("Fear Gem", 20, "Common"),
  ("Galvasphere", 20, "Rare"),
  ("Ghost Ampoule", 20, "Common"),
  ("Glimmering Missive", 20, "Common"),
  ("Golden-Cased Bullet (Standard)", 20, "Uncommon"),
  ("Grindlegrub Steak", 20, "Uncommon"),
  ("Healing Vapor (Lesser)", 20, "Common"),
  ("Invisibility Potion", 20, "Uncommon"),
  ("Magnetic Suit", 20, "Common"),
  ("Mortalis Coin", 20, "Common"),
  ("Oozepick", 20, "Uncommon"),
  ("Potion Patch (Lesser)", 20, "Common"),
  ("Taster's Folly", 20, "Common"),
  ("Undead Detection Dye", 20, "Uncommon"),
  ("Zerk", 20, "Common"),
  ("Clinging Ooze Snare", 25, "Rare"),
  ("Ice Slick Snare", 40, "Uncommon"),
  ("Rhythm Bone (Greater)", 64, "Uncommon"),
  ("Striking", 65, "Common"),
  ("Merciful", 70, "Common"),
  ("Air Cartridge Firing System", 75, "Uncommon"),
  ("Compound Eyes", 75, "Common"),
  ("Deck of Mischief", 75, "Uncommon"),
  ("Ghost Touch", 75, "Common"),
  ("Hag Eye (Oracular)", 75, "Rare"),
  ("Jug of Fond Remembrance", 75, "Common"),
  ("Mortar of Hidden Meaning", 75, "Common"),
  ("Reinforcing Rune (Minor)", 75, "Common"),
  ("Sealing Chest (Lesser)", 75, "Uncommon"),
  ("Smuggler's Sack (Type I)", 75, "Uncommon"),
  ("Spacious Pouch (Type I)", 75, "Common"),
  ("Wand of Mercy (1st-Level Spell)", 75, "Common"),
  ("Wand of the Pampered Pet", 75, "Common"),
  ("Composer Staff", 80, "Common"),
  ("Distracting Carapace", 80, "Common"),
  ("Healer's Gloves", 80, "Common"),
  ("Hosteling Statuette", 80, "Uncommon"),
  ("Hunter's Arrowhead", 80, "Rare"),
  ("Lifting Belt", 80, "Common"),
  ("Pillow Shield", 80, "Uncommon"),
  ("Shapespeak Mask", 80, "Common"),
  ("Spyglass (Fine)", 80, "Common"),
  ("Stargazer's Spyglass", 80, "Uncommon"),
  ("Superior Catch Pole", 80, "Common"),
  ("Wand of Crushing Leaps", 80, "Common"),
  ("Wand of Shrouded Step", 80, "Common"),
  ("Wayfinder of Rescue", 80, "Uncommon"),
  ("Aeon Stone (Azure Briolette)", 85, "Uncommon"),
  ("Belt of Good Health", 85, "Common"),
  ("Demon Mask", 85, "Common"),
  ("Diver's Gloves (Lesser)", 85, "Uncommon"),
  ("Extraction Cauldron", 85, "Uncommon"),
  ("Hag Eye (Frightful)", 85, "Rare"),
  ("Highhelm Drill (Mark I)", 85, "Uncommon"),
  ("Noppera-Bo Hood", 85, "Rare"),
  ("Talisman Cord (Lesser)", 85, "Uncommon"),
  ("Wovenwood Shield (Minor)", 85, "Uncommon"),
  ("Aeon Stone (Clear Quartz Octagon)", 90, "Uncommon"),
  ("Animal Staff", 90, "Common"),
  ("Ankhrav Duster", 90, "Uncommon"),
  ("Bagpipes of Turmoil", 90, "Common"),
  ("Cloak of Repute", 90, "Common"),
  ("Draxie's Recipe Book", 90, "Common"),
  ("Drums of War", 90, "Common"),
  ("Entertainer's Lute", 90, "Common"),
  ("Exquisite Sword Cane", 90, "Common"),
  ("Five-Feather Wreath", 90, "Common"),
  ("Mentalist's Staff", 90, "Common"),
  ("Pipes of Compulsion", 90, "Uncommon"),
  ("Poisoner's Staff", 90, "Uncommon"),
  ("Rhinoceros Mask", 90, "Uncommon"),
  ("Seer's Flute", 90, "Uncommon"),
  ("Spiny Lodestone", 90, "Common"),
  ("Staff of Healing", 90, "Common"),
  ("Symbol of Conflict", 90, "Uncommon"),
  ("Thorn Triad", 90, "Common"),
  ("Trickster's Mandolin", 90, "Common"),
  ("Atmospheric Staff (Lesser)", 95, "Uncommon"),
  ("Camouflaging Chromatophores (Lesser)", 95, "Uncommon"),
  ("Sextant of the Night", 95, "Common"),
  ("Alchemical Chart (Lesser)", 100, "Common"),
  ("Alchemist Goggles", 100, "Common"),
  ("Alchemist Goggles", 100, "Common"),
  ("Arcane Scroll Case of Simplicity", 100, "Uncommon"),
  ("Bane", 100, "Uncommon"),
  ("Blast Lance", 100, "Uncommon"),
  ("Cape of Justice", 100, "Rare"),
  ("Divine Scroll Case of Simplicity", 100, "Uncommon"),
  ("Dragon's Breath (1st-Level Spell)", 100, "Uncommon"),
  ("Drake Rifle", 100, "Uncommon"),
  ("Dread Helm", 100, "Common"),
  ("Handwraps of Mighty Blows (+1 striking)", 100, "Common"),
  ("Lawbringer's Lasso", 100, "Uncommon"),
  ("Magic Weapon (+1 Striking)", 100, "Common"),
  ("Marvelous Calliope", 100, "Uncommon"),
  ("Mask of Mercy", 100, "Common"),
  ("Memory Guitar", 100, "Common"),
  ("Occult Scroll Case of Simplicity", 100, "Uncommon"),
  ("Pickpocket's Tailoring", 100, "Uncommon"),
  ("Primal Scroll Case of Simplicity", 100, "Uncommon"),
  ("Shining Wayfinder", 100, "Uncommon"),
  ("Sleeves of Storage", 100, "Common"),
  ("Spore Shepherd's Staff", 100, "Uncommon"),
  ("Spore Shepherd's Staff (Major)", 100, "Uncommon"),
  ("Sturdy Shield (Minor)", 100, "Common"),
  ("Wand of Legerdemain (1st-Level Spell)", 100, "Common"),
  ("Wand of Pernicious Poison (1st-Level Spell)", 100, "Common"),
  ("Wand of Reaching (1st-Level Spell)", 100, "Common"),
  ("Wand of Widening (1st-rank Spell)", 100, "Common"),
  ("Warcaller's Chime of Destruction", 100, "Uncommon"),
  ("Wand of Mental Purification (1st-Level Spell)", 110, "Common"),
  ("Fulmination Fang", 115, "Uncommon"),
  ("Gyroscopic Stabilizer", 115, "Uncommon"),
  ("Bag of Weasels", 0, "Rare")
]

const itens5 = [
  ["Diluted Hype", 20, "Uncommon"],
  ["Weapon Shot (Lesser)", 20, "Common"],
  ["Absolute Solvent (Lesser)", 21, "Common"],
  ["Amphisbaena Spittle", 21, "Common"],
  ["Blister Ammunition (Lesser)", 21, "Common"],
  ["Clown Monarch", 21, "Common"],
  ["Elemental Ammunition (Moderate)", 21, "Common"],
  ["Fu Water", 21, "Common"],
  ["Fungal Walk Musk", 21, "Common"],
  ["Gadget Skates", 21, "Uncommon"],
  ["Potion of Leaping", 21, "Common"],
  ["Universal Solvent (Moderate)", 21, "Common"],
  ["Discord Fulu", 22, "Common"],
  ["Eroding Bullet", 22, "Uncommon"],
  ["Rhino Shot", 22, "Uncommon"],
  ["Sampling Ammunition", 22, "Common"],
  ["Sea Touch Elixir (Lesser)", 22, "Common"],
  ["Sneaky Key", 22, "Common"],
  ["Stage Fright Missive", 22, "Common"],
  ["Stone Body Mutagen (Lesser)", 22, "Common"],
  ["Shark Tooth Charm", 23, "Common"],
  ["Tin Cobra", 23, "Uncommon"],
  ["Goblin-Eye Orb", 24, "Common"],
  ["Ichthyosis Mutagen", 24, "Rare"],
  ["Imp Shot", 24, "Common"],
  ["Serpent Oil (Moderate)", 24, "Common"],
  ["Alkenstar Ice Wine", 25, "Uncommon"],
  ["Apotropaic Fulu", 25, "Common"],
  ["Bane Ammunition (Moderate)", 25, "Common"],
  ["Bola Shot", 25, "Common"],
  ["Cheetah's Elixir (Moderate)", 25, "Common"],
  ["Cooperative Waffles (Greater)", 25, "Common"],
  ["Cryomister (Moderate)", 25, "Uncommon"],
  ["Dagger of Eternal Sleep", 25, "Uncommon"],
  ["Depth Charge (I)", 25, "Common"],
  ["Dragon's Blood Pudding (Moderate)", 25, "Uncommon"],
  ["Elven Absinthe", 25, "Common"],
  ["Exploding Shield", 25, "Common"],
  ["Eye of Enlightenment", 25, "Common"],
  ["False Death", 25, "Uncommon"],
  ["Fearcracker", 25, "Common"],
  ["Firestarter Pellets", 25, "Common"],
  ["Flame Drake Snare", 25, "Uncommon"],
  ["Freezing Ammunition", 25, "Common"],
  ["Fulu of the Drunken Monkey", 25, "Common"],
  ["Fulu of the Stoic Ox", 25, "Common"],
  ["Gecko Pads", 25, "Uncommon"],
  ["Golden Branding Iron", 25, "Uncommon"],
  ["Gravemist Taper", 25, "Common"],
  ["Healer's Gel (Lesser)", 25, "Common"],
  ["Heartening Missive (Butterfly)", 25, "Common"],
  ["Life Salt", 25, "Common"],
  ["Mustard Powder", 25, "Common"],
  ["Oil of Revelation", 25, "Common"],
  ["Privacy Ward Fulu (Room)", 25, "Rare"],
  ["Pummeling Snare", 25, "Uncommon"],
  ["Reducer Round", 25, "Uncommon"],
  ["Replacement Filter (Level 5)", 25, "Uncommon"],
  ["Resurrection Tea", 25, "Uncommon"],
  ["Shimmering Dust", 25, "Common"],
  ["Sixfingers Elixir (Lesser)", 25, "Uncommon"],
  ["Sky Serpent Bolt", 25, "Uncommon"],
  ["Skyfisher Vapors", 25, "Common"],
  ["Spider Venom", 25, "Common"],
  ["Statue Skin Salve", 25, "Uncommon"],
  ["Thunderbird Tuft (Moderate)", 25, "Common"],
  ["Tracking Fulu", 25, "Common"],
  ["Tricky Liniment", 25, "Common"],
  ["Viperous Elixir (Lesser)", 25, "Common"],
  ["Wet Shock Snare", 25, "Uncommon"],
  ["Beckoning Cat Amulet", 26, "Uncommon"],
  ["Sprite Apple (Chartreuse)", 26, "Common"],
  ["Eagle-Eye Elixir (Moderate)", 27, "Common"],
  ["Egg Cream Fizz", 27, "Common"],
  ["Golden Chrysalis", 27, "Common"],
  ["Freeze Ammunition", 28, "Common"],
  ["Ginger Chew", 28, "Common"],
  ["Rhino Hide Brooch", 28, "Uncommon"],
  ["Soothing Tonic (Moderate)", 28, "Common"],
  ["3rd-rank Scroll", 30, "Common"],
  ["Alchemist's Damper", 30, "Uncommon"],
  ["Animal Pheromones (Lesser)", 30, "Common"],
  ["Contagion Metabolizer (Lesser)", 30, "Common"],
  ["Copper Penny", 30, "Common"],
  ["Crackling Bubble Gum (Lesser)", 30, "Common"],
  ["Cytillesh", 30, "Uncommon"],
  ["Demortification Oil", 30, "Rare"],
  ["Dupe's Gold Nugget", 30, "Uncommon"],
  ["Electromuscular Stimulator", 30, "Rare"],
  ["Elixir of Life (Lesser)", 30, "Common"],
  ["Emerald Grasshopper", 30, "Common"],
  ["Euphoric Loop", 30, "Common"],
  ["Familiar Morsel", 30, "Common"],
  ["Frozen Lava", 30, "Common"],
  ["Grease Snare", 30, "Rare"],
  ["Green Wyrmling Breath Potion", 30, "Common"],
  ["Hippogriff in a Jar", 30, "Common"],
  ["Mad Mammoth's Juke", 30, "Rare"],
  ["Malleable Clay", 30, "Uncommon"],
  ["Midnight Milk (Experimental)", 30, "Rare"],
  ["Moonlit Spellgun (Lesser)", 30, "Common"],
  ["Necrobinding Serum", 30, "Rare"],
  ["Numbing Tonic (Lesser)", 30, "Common"],
  ["Oily Button", 30, "Uncommon"],
  ["Pheromone Flare (Lesser)", 30, "Common"],
  ["Poracha Fulu", 30, "Uncommon"],
  ["Potion of Disguise (Lesser)", 30, "Uncommon"],
  ["Pucker Pickle", 30, "Common"],
  ["Silver Orb (Lesser)", 30, "Uncommon"],
  ["Soothing Powder (Lesser)", 30, "Common"],
  ["Sparking Spellgun (Lesser)", 30, "Common"],
  ["Spellstrike Ammunition (Type II)", 30, "Common"],
  ["Spiritual Warhorn (Lesser)", 30, "Common"],
  ["Thousand-Pains Fulu (Stone)", 30, "Uncommon"],
  ["Tiger Menuki", 30, "Common"],
  ["Unsullied Blood (Lesser)", 30, "Uncommon"],
  ["Wine of the Blood", 30, "Rare"],
  ["Blindpepper Bomb", 40, "Uncommon"],
  ["Potion of Resistance (Lesser)", 45, "Common"],
  ["Slick", 45, "Common"],
  ["Wounding Oil", 45, "Uncommon"],
  ["Knight's Maintenance Kit", 50, "Uncommon"],
  ["War Saddle", 50, "Uncommon"],
  ["Shadow", 55, "Common"],
  ["Nightpitch", 60, "Common"],
  ["Recording Rod (Reusable)", 60, "Uncommon"],
  ["Liar's Board", 90, "Uncommon"],
  ["Floorbell", 120, "Uncommon"],
  ["Large Bore Modifications", 120, "Uncommon"],
  ["Anylength Rope (Moderate)", 125, "Common"],
  ["Assisting", 125, "Common"],
  ["Book of Translation (Advanced)", 125, "Uncommon"],
  ["Chaos Collar", 125, "Common"],
  ["Diplomat's Badge", 125, "Common"],
  ["Earthbinding", 125, "Common"],
  ["Magnifying Glass of Elucidation", 125, "Uncommon"],
  ["Nightbreeze Machine", 125, "Uncommon"],
  ["Pipe of Dancing Smoke", 125, "Uncommon"],
  ["Remote Trigger", 125, "Common"],
  ["Rope of Climbing (Moderate)", 125, "Common"],
  ["Skeleton Key", 125, "Common"],
  ["Twisting Twine (Moderate)", 125, "Common"],
  ["Wondrous Figurine (Stuffed Fox)", 125, "Uncommon"],
  ["Aeon Stone (Agate Ellipsoid)", 130, "Uncommon"],
  ["Magnetic Shield", 130, "Common"],
  ["Spectacles of Understanding", 130, "Uncommon"],
  ["Stanching", 130, "Uncommon"],
  ["Tlil Mask", 130, "Uncommon"],
  ["Tome of Restorative Cleansing (Lesser)", 130, "Common"],
  ["Waverider Barding", 130, "Uncommon"],
  ["Wind at Your Back", 130, "Common"],
  ["Collar of the Shifting Spider", 133, "Common"],
  ["Boots of Free Running (Lesser)", 135, "Uncommon"],
  ["Cape of Illumination (Lesser)", 135, "Uncommon"],
  ["Mirror Goggles (Lesser)", 135, "Common"],
  ["Pocket Stage", 138, "Common"],
  ["Cold Iron Armor (Low-Grade)", 140, "Common"],
  ["Corrosive Engravings", 140, "Common"],
  ["Cunning", 140, "Uncommon"],
  ["Hooked", 140, "Rare"],
  ["Raiment", 140, "Common"],
  ["Resonating Fork", 140, "Common"],
  ["Silver Armor (Low-Grade)", 140, "Common"],
  ["Sisterstone Armor (Low-Grade)", 140, "Rare"],
  ["Trollhound Pick", 140, "Common"],
  ["Wondrous Figurine (Candy Constrictor)", 140, "Uncommon"],
  ["Aeon Stone (Preserving)", 150, "Uncommon"],
  ["Alicorn Lance", 150, "Uncommon"],
  ["Amphisbaena Handwraps", 150, "Uncommon"],
  ["Anglerfish Lantern", 150, "Common"],
  ["Armory Bracelet (Lesser)", 150, "Common"],
  ["Astrolabe of Falling Stars", 150, "Uncommon"],
  ["Auspicious Scepter", 150, "Common"],
  ["Bomb Coagulant Alembic", 150, "Common"],
  ["Bravery Baldric (Fleet)", 150, "Common"],
  ["Brazier of Harmony", 150, "Common"],
  ["Cinderclaw Gauntlet", 150, "Uncommon"],
  ["Conundrum Spectacles", 150, "Uncommon"],
  ["Corpseward Pendant", 150, "Uncommon"],
  ["Desiccating Scepter", 150, "Rare"],
  ["Dog-Bone Knife", 150, "Uncommon"],
  ["Dreamweb Object (Standard-Grade)", 150, "Rare"],
  ["Grim Ring", 150, "Uncommon"],
  ["Helmsman's Recourse", 150, "Common"],
  ["Hydrocannon", 150, "Uncommon"],
  ["Infiltrator's Accessory", 150, "Common"],
  ["Mask of the Mantis", 150, "Uncommon"],
  ["Obsidian Goggles", 150, "Common"],
  ["Ooze Skin", 150, "Common"],
  ["Pacifying", 150, "Common"],
  ["Paired", 150, "Uncommon"],
  ["Poisonous Dagger", 150, "Common"],
  ["Quick Runner's Shirt", 150, "Uncommon"],
  ["Scizore of the Crab", 150, "Common"],
  ["Secret-Keeper's Mask (Gray Master)", 150, "Rare"],
  ["Serpent Dagger", 150, "Common"],
  ["Shade Hat", 150, "Uncommon"],
  ["Spirit-Singer", 150, "Rare"],
  ["Sun Wheel", 150, "Rare"],
  ["True Name Amulet (Lesser)", 150, "Rare"],
  ["Vanishing Wayfinder", 150, "Uncommon"],
  ["Vitalizing", 150, "Common"],
  ["Caterwaul Sling", 155, "Common"],
  ["Grasp of Droskar", 155, "Rare"],
  ["Thundercrasher", 155, "Uncommon"],
  ["Arboreal Boots", 160, "Common"],
  ["Armor Potency (+1)", 160, "Common"],
  ["Beastmaster's Sigil", 160, "Common"],
  ["Bort's Blessing", 160, "Rare"],
  ["Burr Shield", 160, "Common"],
  ["Darkvision Scope", 160, "Common"],
  ["Eternal Eruption", 160, "Common"],
  ["Fearsome", 160, "Common"],
  ["Fleshgem (Combat)", 160, "Uncommon"],
  ["Folding Drums", 160, "Uncommon"],
  ["Furnace of Endings", 160, "Uncommon"],
  ["Guiding Cajon Drum", 160, "Common"],
  ["Heartripper Blade", 160, "Rare"],
  ["Heated Cloak", 160, "Uncommon"],
  ["Holy Prayer Beads", 160, "Uncommon"],
  ["Living Leaf Weave", 160, "Common"],
  ["Magic Armor (+1)", 160, "Common"],
  ["Magic Wand (2nd-rank Spell)", 160, "Common"],
  ["Merchant's Guile", 160, "Uncommon"],
  ["Metronomic Hammer", 160, "Uncommon"],
  ["Poison Concentrator (Lesser)", 160, "Common"],
  ["Ring of Minor Arcana", 160, "Uncommon"],
  ["Ring of the Tiger", 160, "Uncommon"],
  ["Ring of the Weary Traveler", 160, "Uncommon"],
  ["Shell of Easy Breathing", 160, "Common"],
  ["Solar Shellflower", 160, "Uncommon"],
  ["Squid Ink Sac", 160, "Common"],
  ["Stalwart's Ring", 160, "Uncommon"],
  ["Tactician's Helm", 160, "Common"],
  ["Thunder Helm", 160, "Uncommon"],
  ["Wand of Caustic Effluence", 160, "Rare"],
  ["Wand of Contagious Frailty", 160, "Common"],
  ["Wand of Continuation (1st-rank Spell)", 160, "Common"],
  ["Wand of Shardstorm (1st-rank Spell)", 160, "Common"],
  ["Warcaller's Chime of Resistance", 160, "Uncommon"],
  ["Warrior's Training Ring", 160, "Uncommon"],
  ["Worldringer", 160, "Uncommon"],
  ["Mariner's Splint", 180, "Uncommon"],
  ["Instructions for Lasting Agony", 200, "Common"],
  ["Sisterstone Ingot", 200, "Rare"]
  ["Tiger Fork", 275, "Uncommon"],
  ["Snowshoes of the Long Trek", 550, "Uncommon"],
  ["Crushing Coils", 0, "Rare"],
  ["Shard of Self-Destruction", 0, "Rare"],
  ["Shrieking Key", 0, "Rare"],
  ["Spurned Lute", 0, "Rare"]
]



function gerar() {
  let ndval = nd.value
  let difval = dificuldade.value
  resultado.innerHTML = ''
  budget(ndval, difval)
  }

  function budget(nd, dificuldade) {

  let budget = tabela[nd][dificuldade];
  resultado.innerHTML = `O valor de budget correspondente é ${budget}`
}